site_name: IMT Edinburgh
theme:
  name: material
  palette:
    scheme: imt
  custom_dir: overrides      
  logo: images/star.png
  favicon: images/favicon.ico
  features:
    - navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigration.top
    #- navigation.expand 
    #- toc.integrate
extra_css:
  - stylesheets/custom.css

  
nav:
  - Branch:
    - About: index.md
    - Finance:
        - Setting Up Subscriptions: subs.md
        - Fighting Fund: fighting-fund.md
        - Buying Books: buy-books.md
        - Buying Papers: buy-papers.md
    - Calendar: calendar.md
  - John Maclean Society (JMS):
      About: jms/about.md
  - Theory:
      - Recommended Reading: reading/recommended.md
      - Reading Groups: reading/groups.md

plugins:
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      write_markdown: false
      binder: false
      binder_service_name: "gh"
      binder_branch: "master"
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_if_no_docstring: true
            show_root_heading: true
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - codehilite
  - admonition
  - footnotes
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  
#extra_css:
#  - stylesheets/extra.css
  
#extra_javascript:
#  - javascripts/config.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://cdn.plot.ly/plotly-latest.min.js
